# Generated by Django 3.1.14 on 2022-01-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationinfo',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='experienceinfo',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='expected_retirement_year',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='first_time_scale_due_year',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='grade_of_post',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='promotion_due_year',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='recreation_leave_due_year',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='second_time_scale_due_year',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='e_tin',
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='institute',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='name_of_exam',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='category',
            field=models.CharField(choices=[('Prof', 'Prof'), ('Admin', 'Administration')], max_length=45),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='driving_license_passport',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(choices=[('Senegalais', 'Senegalaise'), ('Francaise', 'Francaise'), ('Others', 'Others')], max_length=45),
        ),
    ]
