# Generated by Django 3.1.14 on 2022-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200419_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='previous_academic_certificate',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=832673, unique=True),
        ),
        migrations.DeleteModel(
            name='PreviousAcademicCertificate',
        ),
    ]
