# Generated by Django 3.1.14 on 2022-01-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20220129_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=60107, unique=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='father_yearly_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='guardian_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='guardian_phone_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
